### ISSUE TITLE
How do you use this in Linux

### ISSUE THREAD

**Issue by ademlabs** [Rinnegatamante/VitaPad#24]
Unable to find any documentation on how to use this on Linux. App installs and starts fine on the Vita.

**Comment by Rinnegatamante** [comment]
Linux port has been made by nyorem. I personally didn't try it.

**Comment by ademlabs** [comment]
Ok I figured it out. It might be obvious to others but for those who are still looking, you need to compile the client app yourself.
Steps:
- Download this repository
- `cd` into the Client directory
- Run `make`
- Run the `VitaPad` compiled binary on your PC.
- Run the `VitaPad` app/server on your Vita. It will display an IP address.
- Type the IP address into the VitaPad client.
- It will connect and the Vita will send keyboard events to your PC.
