### ISSUE TITLE
Client linux compilation error

### ISSUE THREAD

**Issue by GrayJack** [Rinnegatamante/VitaPad#3]
When compiling it gives me this error:

> (.text+0xd3): undefined reference to `xcb_disconnect'
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'linux' failed
make: *** [linux] Error 1

**Comment by Rinnegatamante** [comment]
The linux port has been made by @nyorem . You should wait for an answer from him.

**Comment by nyorem** [comment]
Removing the '-static' flag from the Makefile did the trick for me.

**Comment by GrayJack** [comment]
Did it for me too, thanks!!
But I'm having another problem, seen that the retrotouch does nothing in the linux version

**Comment by nyorem** [comment]
On my machine, it is working: the left part of the retrotouch is a left click and the right one is a right click.
You can test if the events are correctly sent by using the `xev` command.

**Comment by GrayJack** [comment]
OH, for some reason it wasn't working that day, today it worked, but... another problem, when open a submenu (that one with copy, paste, etc) the right and left mouse click stops to work.
To make sure, I used xev commmand and with the submenu open, it really didn't work.

**Comment by nyorem** [comment]
Ok. You're right. I will look at it (probably this week end).

**Comment by nyorem** [comment]
Can you test my fork? It seems to work on my machine.
Note that when "clicking", you also need to have a thumb on the front screen.

**Comment by GrayJack** [comment]
Sorry for the late reply, didn't had the time, I just tested and now it works!!!
Thanks very much for the atention :3
