### ISSUE TITLE
Example configuration files

### ISSUE THREAD

**Issue by elmanytas** [Rinnegatamante/VitaPad#9]
Hi

I compiled vitapad in Ubuntu and mouse works. :-)

There are not any linux.xml or windows.xml config files in repository.

How example config files can be downloaded?

Thank you

**Comment by GueGuerreiro** [comment]
According to PR https://github.com/Rinnegatamante/VitaPad/pull/2#issuecomment-242965709, example files shouldn't be included in the repository, and instead should be included on the releases.

Currently the repo doesn't have any releases, so I created PR https://github.com/Rinnegatamante/VitaPad/pull/12 that should add default configuration files for Windows and Linux as well as a README.md. I think it would be a nice addition to get people started initially.

**Comment by elmanytas** [comment]
Thank you!
